django_diplom/authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('reg/', views.reg, name='reg'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('myacc/', views.account, name='account'),


]

django_diplom/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('addcart/<slug:product_slug>/', views.add_to_cart, name='add_to_cart'),
    path('addcart_addon/<slug:addon_slug>/', views.add_to_cart_addon, name='add_to_cart_addon'),

    path('showcart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
   path('makeorder/', views.MakeOrder, name='make_order'),

    path('addcart/removeproduct/<slug:product_slug>/', views.remove_product, name='remove_product'),
    path('addcart/change_quantity/<slug:product_slug>/', views.change_quantity, name='change_quantity'),
path('addcart_addon/removeproduct/<slug:addon_slug>/', views.remove_addon, name='remove_addon'),
    path('addcart_addon/change_quantity/<slug:addon_slug>/', views.change_quantity_addon, name='change_quantity_addon'),

]

django_diplom/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),
    path('men/', views.MenTemplate.as_view(), name='Men'),
    path('women/', views.women, name='Women'),
    path('kids/', views.kids, name='Kids'),
    path('accessories/', views.accessory, name='Accessory'),

    path('category/<slug:category_slug>/', views.one_cat, name='one_cat'),
    path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),

    # path('ad/', views.addons, name='addons'),
    # path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),
    # path('onec/', views.one_cat, name='one_cat'),
    # path('onec/<slug:product_slug>/', views.product_views, name='product'),

    # path('product/', views.product_views, name='product'),
    # path('category/<slug:category_slug>/', views.category_view, name='category_view'),
    # path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    # path('category/<slug:category_slug>/', views.cat_review, name='cat_review'),
    # path('product/<slug:product_slug>/', views.prod_review, name='prod_review'),
    # path('cat/<slug:category_slug>/', views.table, name='table'),

]

django_diplom/contact_form/urls.py
from django.urls import path
from . import views

app_name = 'contact_form'
urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("contact", views.contact, name="contact"),
]

django_diplom/django_diplom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views
from django_diplom import settings




urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('authentication.urls')),
    path('cart/', include('cart.urls')),
    path('news/', include('news.urls')),
    path('contactwithus/', include('contact_form.urls'))

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_diplom/news/urls.py
from django.urls import path
from . import views

app_name = 'new'

urlpatterns = [

    path('news/', views.new, name='new'),
]

django_diplom/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %} магазин {% endblock %}</title>
    {% block styles %}

    {% endblock %}
</head>
<body>
{% comment %}<ul>
    {% for item in nav_items %}
    <li> <a href="{% url 'catalog:one_cat' item.slug %}">{{item.name}} </a></li>
    </li>
    {% endfor %}
</ul>{% endcomment %}
<a href="{% url 'catalog:Men' %}">Мужское</a>
<a href="{% url 'catalog:Women' %}">Женское</a>
<a href="{% url 'catalog:Kids' %}">Детское</a>
<a href="{% url 'catalog:Accessory' %}">Аксессуары </a>


{#<a href="{% url 'new:new' %}">Новости</a>#}
{% if request.user.is_authenticated %}
    <span>{{ request.user.username }}</span>
    {% if user.avatar %}

    <img src="{{ user.avatar.url }}" height="25" width="25">
        {% endif %}
    <a href="{% url 'authentication:logout' %}">Выйти</a>

{% else %}

  <a href="{% url 'authentication:login' %}">Войти</a>


{% endif %}

<a href="{% url 'cart:cart' %}  ">Корзина({{ total_quantity }})</a>


<a href="{% url 'authentication:account' %}">MyAcc</a>

<a href="{% url 'catalog:home' %}">Home</a>

<br/><br>

<br/><br>








<a href="{% url 'contact_form:contact' %}">У вас есть вопрос?</a>
{#{% load staticfiles %}#}
<a href="https://vk.com/share.php?url=https://evileg.com/ru/{{ article.get_absolute_url }}"
   target="_blank" rel="nofollow">
{#    <img src="{% static 'images/social/vk.png' %}">#}
</a>
<a href="https://twitter.com/share?url=https://evileg.com/ru/{{ article.get_absolute_url }}"
   target="_blank" rel="nofollow">
{#    <img src="{% static 'images/social/twitter.png' %}">#}
</a>
<a href="https://www.facebook.com/sharer/sharer.php?u=https://evileg.com/ru/{{ article.get_absolute_url }}"
   target="_blank" rel="nofollow">
{#    <img src="{% static 'images/social/facebook.png' %}">#}
</a>
<a href="https://plus.google.com/share?url=https://evileg.com/ru/{{ article.get_absolute_url }}"
   target="_blank" rel="nofollow">
{#    <img src="{% static 'images/social/google-plus.png' %}">#}
</a>
<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://evileg.com/ru/{{ article.get_absolute_url }}"
   target="_blank" rel="nofollow">
{#    <img src="{% static 'images/social/linkedin.png' %}">#}
</a>


   {% block content %}
    {% endblock %}
{% block scripts %}
{% endblock %}


</body>
</html>

django_diplom/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>registration</title>
    <style>
     input {
         display: block;
     }

    </style>

</head>
<body>
<form>
  <label for="email">email:</label>
 <input type="email">
  <label for="password">password:</label>
  <input type="password">
  <label for="password2">password2:</label>
<input type="password2">
     <label for="date">выберите дату рождения:</label>
 <input type="date">
  <label for="file">выберите аву:</label>
 <input type="file">


    <img src="some_img.jpg">


  <label for="text">Расскажите о себе:</label>
    <input type="text">
    <input type="submit">
    </form>
</body>
</html>

django_diplom/templates/ищщеыек.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="css/bootstrap.min.css">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- Подключение JavaScript -->
    <!-- Сначала jQuery, затем Popper.js, затем Bootstrap JS -->
    <script src="js/jquery-3.3.1.slim.min.js"></script>
    <script src="js/popper.min.js" ></script>
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>