django_diplom/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('addcart/<slug:product_slug>/', views.add_to_cart, name='add_to_cart'),
    path('addcart_addon/<slug:addon_slug>/', views.add_to_cart_addon, name='add_to_cart_addon'),

    path('showcart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
   path('makeorder/', views.MakeOrder, name='make_order'),

    path('addcart/removeproduct/<slug:product_slug>/', views.remove_product, name='remove_product'),
    path('addcart/change_quantity/<slug:product_slug>/', views.change_quantity, name='change_quantity'),
path('addcart_addon/removeproduct/<slug:addon_slug>/', views.remove_addon, name='remove_addon'),
    path('addcart_addon/change_quantity/<slug:addon_slug>/', views.change_quantity_addon, name='change_quantity_addon'),

]

django_diplom/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),
    path('men/', views.MenTemplate.as_view(), name='Men'),
    path('women/', views.women, name='Women'),
    path('kids/', views.kids, name='Kids'),
    path('accessories/', views.accessory, name='Accessory'),

    path('category/<slug:category_slug>/', views.one_cat, name='one_cat'),
    path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),

    # path('ad/', views.addons, name='addons'),
    # path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),
    # path('onec/', views.one_cat, name='one_cat'),
    # path('onec/<slug:product_slug>/', views.product_views, name='product'),

    # path('product/', views.product_views, name='product'),
    # path('category/<slug:category_slug>/', views.category_view, name='category_view'),
    # path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    # path('category/<slug:category_slug>/', views.cat_review, name='cat_review'),
    # path('product/<slug:product_slug>/', views.prod_review, name='prod_review'),
    # path('cat/<slug:category_slug>/', views.table, name='table'),

]

django_diplom/django_diplom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views
from django_diplom import settings




urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('authentication.urls')),
    path('cart/', include('cart.urls')),
    path('news/', include('news.urls')),
    path('contactwithus/', include('contact_form.urls'))

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_diplom/cart/models.py
from django.db import models
from django.utils import timezone

from django_diplom import settings


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=64, verbose_name=' Полное имя')
    phone_number = models.CharField(max_length=16, verbose_name='номер телефона')
    email = models.EmailField(max_length=32, verbose_name='email')
    orders = models.ManyToManyField('Order', verbose_name='Заказы', related_name='related_customer')

    def __str__(self):
        return str(self.id)


class Cart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.Model)
    date_created = models.DateTimeField(auto_now=True)
    checked_out = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)

class CartProduct(models.Model):
    product = models.ForeignKey('catalog.Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)

    def product_price(self):
        full_price = self.product.price * self.product.quantity
        return full_price


class CartAddon(models.Model):
    addon = models.ForeignKey('catalog.Addon', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

    def addon_price(self):
        full_price_addon = self.addon.price * self.addon.quantity
        return full_price_addon


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'новый заказ'),
        (STATUS_IN_PROGRESS, 'закакз в обработке'),
        (STATUS_READY, 'заказ готов'),
        (STATUS_COMPLETED, 'заказ выполнен')

    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'самовывоз'),
        (BUYING_TYPE_DELIVERY, 'доставка')
    )
    customer = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE,
                                 related_name='related_orders')

    first_name = models.CharField(max_length=100, verbose_name='имя')
    last_name = models.CharField(max_length=100, verbose_name='фамилия')
    phone = models.CharField(max_length=100, verbose_name='телефон')
    cart = models.ForeignKey('Cart', verbose_name='корзина', on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(max_length=100, verbose_name='email',null=True, blank=True)
    address = models.CharField(max_length=100, verbose_name='адресс', null=True, blank=True)
    status = models.CharField(max_length=100, verbose_name='статус заказа ', choices=STATUS_CHOICES, default=STATUS_NEW)
    buying_type = models.CharField(
        max_length=100,
        verbose_name="тип заказа",
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF)
    comment = models.TextField(verbose_name='комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='время создания заказа')
    order_date = models.DateTimeField(verbose_name='дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)

django_diplom/catalog/models.py
from colorfield.fields import ColorField
from django.db import models

gender = (
    ('male', 'male'),
    ('female', 'female'),
    ('kids', 'kids'),
    ('accessory', 'accessory'),
)

COLOR_CHOICES = [
    ("#FFFFFF", "white"),
    ("#000000", "black")

]


class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='описание')
    slug = models.SlugField(max_length=40, unique=True)
    gender = models.CharField(default='', max_length=9, choices=gender, verbose_name="gender")

    def __str__(self):
        return self.name


class Addon(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='описание')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='цена')
    slug = models.SlugField(max_length=40, unique=True)
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name


class AddonImage(models.Model):
    image = models.ImageField(blank=True, null=True, upload_to='images', help_text='150x150px',
                              verbose_name='изображение')
    addon = models.ForeignKey('Addon', on_delete=models.CASCADE)


class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='описание')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='цена')
    slug = models.SlugField(max_length=40, unique=True)
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    addons = models.ManyToManyField("Addon", blank=True)
    quantity = models.PositiveIntegerField(default=1)




    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(blank=True, null=True, upload_to='images', help_text='150x150px',
                              verbose_name='изображение')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)


class ProductSpecification(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование характеристики')

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

    def __str__(self):
        return self.name


class ProductSpecificationValue(models.Model):
    specification = models.ForeignKey('ProductSpecification', on_delete=models.CASCADE)
    value = models.CharField(max_length=128, verbose_name='Значение характеристики')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Значение характеристики'
        verbose_name_plural = 'Значения характеристик'

    def __str__(self):
        return f'{self.specification.name} - {self.value}'


class AddonSpecification(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование характеристики')

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

    def __str__(self):
        return self.name


class AddonSpecificationValue(models.Model):
    specification = models.ForeignKey('AddonSpecification', on_delete=models.CASCADE)
    value = models.CharField(max_length=128, verbose_name='Значение характеристики')
    product = models.ForeignKey('Addon', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Значение характеристики'
        verbose_name_plural = 'Значения характеристик'

    def __str__(self):
        return f'{self.specification.name} - {self.value}'

django_diplom/cart/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone','email', 'address', 'buying_type', 'order_date', 'comment'
        )

django_diplom/cart/views.py
from typing import Optional, Any, Dict

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView

from catalog.models import Product, Addon, Category
from cart.models import CartProduct, CartAddon, Customer, Cart
from django_diplom.settings import EMAIL_HOST_USER

from .forms import OrderForm

# add_to_cart/hamurger/?is_addon=0
from .mixins import CartMixin
from .utils import recalc_cart


def add_to_cart(request, product_slug):
    slug_product = Product.objects.get(slug=product_slug)

    new_cart, is_new_cart = Cart.objects.get_or_create(user=request.user, checked_out=False)
    new_product, _ = CartProduct.objects.get_or_create(product=slug_product, cart=new_cart)

    return redirect(reverse('catalog:home'))


def add_to_cart_addon(request, addon_slug):
    slug_addon = Addon.objects.get(slug=addon_slug)

    new_cart, is_new_cart = Cart.objects.get_or_create(user=request.user, checked_out=False)
    new_addon, _ = CartAddon.objects.get_or_create(addon=slug_addon, cart=new_cart)

    return redirect(reverse('catalog:home'))


def cart(request):
    if not request.user.is_authenticated:
        return redirect(reverse('catalog:home'))

    user_cart = Cart.objects.filter(user=request.user, checked_out=False).first()
    if not user_cart:
        user_cart = Cart.objects.create(user=request.user)

    cart_product = CartProduct.objects.filter(cart=user_cart)
    cart_addon = CartAddon.objects.filter(cart=user_cart)

    is_checked_out = False

    context = {
        'total': cart_price(request),
        'cart_product': cart_product,
        'cart_addon': cart_addon,

    }
    return render(request, 'cart/cart.html', context)


def remove_product(request, product_slug):
    slug_product = Product.objects.get(slug=product_slug)
    old_cart = Cart.objects.filter(user=request.user, checked_out=False).first()
    product = CartProduct.objects.get(product=slug_product, cart=old_cart)
    product.delete()

    return redirect(reverse('cart:cart'))


def remove_addon(request, addon_slug):
    slug_addon = Addon.objects.get(slug=addon_slug)
    old_cart = Cart.objects.filter(user=request.user, checked_out=False).first()
    addon = CartAddon.objects.get(addon=slug_addon, cart=old_cart)
    addon.delete()

    return redirect(reverse('cart:cart'))


def parse_int(value: int, default: Optional[Any] = None) -> Optional[int]:
    try:
        return int(value)
    except (ValueError, TypeError):
        return default


def change_quantity(request, product_slug):
    if request.method == 'POST':

        full_quantity = parse_int(request.POST.get('quantity'))
        product = Product.objects.get(slug=product_slug)
        if full_quantity:
            product.quantity = int(full_quantity)
            changed = False
            product.save()
    return redirect(reverse('cart:cart'))


def change_quantity_addon(request, addon_slug):
    if request.method == 'POST':

        full_quantity = parse_int(request.POST.get('quantity'))
        addon = Addon.objects.get(slug=addon_slug)
        if full_quantity:
            addon.quantity = int(full_quantity)
            addon.save()
    return redirect(reverse('cart:cart'))


def cart_price(request):
    cart = Cart.objects.filter(user=request.user, checked_out=False).prefetch_related("cartproduct_set").first()
    total = 0

    for product in cart.cartproduct_set.all():
        total += product.product_price()
    for addon in cart.cartaddon_set.all():
        total += addon.addon_price()

    return total


# def cart_quantity(request):
#     user_cart = Cart.objects.filter(user=request.user, checked_out=False).first()
#
#     cart_product = CartProduct.objects.filter(cart=user_cart).count()
#     cart_addon = CartAddon.objects.filter(cart=user_cart).count()
#     total_quantity = cart_addon + cart_product
#
#     return total_quantity


def checkout(request):
    user = request.user
    user_cart = Cart.objects.filter(user=request.user, checked_out=False).first()
    cart_product = CartProduct.objects.filter(cart=user_cart)
    cart_addon = CartAddon.objects.filter(cart=user_cart)
    form = OrderForm(request.POST or None)

    is_checked_out = False

    if not user_cart:
        return redirect(reverse('catalog:home'))
    context = {
        'cart_product': cart_product,
        'cart_addon': cart_addon,
        'total': cart_price(request),
        'form': form

    }
    return render(request, 'cart/checkout.html', context)


def MakeOrder(request):
    cart = Cart.objects.filter(user=request.user)
    if request.method == 'POST':
        form = OrderForm(request.POST)
        customer = Customer.objects.get(user=request.user)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone = form.cleaned_data['phone']
            new_order.email = form.cleaned_data['email']
            new_order.address = form.cleaned_data['address']
            new_order.buying_type = form.cleaned_data['buying_type']
            new_order.order_date = form.cleaned_data['order_date']
            new_order.comment = form.cleaned_data['comment']
            new_order.save()

            new_order.cart = cart

            subject = 'привет'
            message = 'php это круто '
            recepient = new_order.email
            send_mail(subject,
                      message, EMAIL_HOST_USER, [recepient], fail_silently=False)

            messages.add_message(request, messages.INFO, ' Спасибо за заказ ,менеджер с вами свяжется !')
            new_order.save()
            customer.orders.add(new_order)
            cart.checked_out = True
            cart.save()

            return redirect(reverse('catalog:home'))
        return redirect((reverse('cart:checkout')))


'''class HomeTemplateView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context['Cart'] = Cart.objects.annotate(
            products_in_cart=Count('cartproduct', distinct=True) + Count('cartaddon', distinct=True))

        return context'''

django_diplom/cart/templates/cart/CART1.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "catalog:one_cat" %}" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}

django_diplom/cart/templates/cart/base_cart.html
{% extends 'base.html' %}

    {% block styles  %}
       {% load static %}
       {{ block.super }}
       <link rel="stylesheet" href="{% static 'cart/styles.css' %}">
    {% endblock %}

django_diplom/cart/templates/cart/cart.html
{% extends 'cart/base_cart.html' %}
{% block title %}Корзина{% endblock %}
{% block content %}

<h5>Корзина</h5>
{%for product in cart_product  %}
    <h5>{{ product.product }} </h5>

    <h3></h3>
    <h3>{{ product.product.quantity }}</h3>
    {% for pr in product.product.productimage_set.all %}
            <img class="product-image" src="{{ pr.image.url }}" alt="{{ product.product.name }}">

        {% endfor %}
    <h3>Сумма:{{ product.product_price }}</h3>
    <form method="post" action="{% url 'cart:change_quantity' product.product.slug %}">
      {% csrf_token %}
    <input type ="number" min="1" max="10" name="quantity">
    <button
        type="submit"
        class="button"

        >Apply</button>
    </form>

    <a href="{% url 'cart:remove_product'  product.product.slug %}">Delete</a>

    {% endfor %}
    {%for addon in cart_addon  %}
    <h5>{{ addon.addon }}</h5>


    <h3>{{ addon.addon_price }}</h3>
    <h3>{{ addon.addon.quantity }}</h3>


    <form method="post" action="{% url 'cart:change_quantity_addon' addon.addon.slug %}">
      {% csrf_token %}
    <input type ="number" min="1" max="10" name="quantity">
    <button
        type="submit"
        class="button"

        >Apply</button>
    </form>

    <a href="{% url 'cart:remove_addon'  addon.addon.slug %}">Delete</a>

    {% endfor %}
    {% if total %}
    <h3>Итого: {{ total }}</h3>
        <h3><a href="{% url 'cart:checkout' %}"><button>перейти к оформлению</button> </a> </h3>
    {% endif %}
{% endblock%}

django_diplom/cart/templates/cart/ccartold.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

django_diplom/cart/templates/cart/checkout.html
{% extends 'base.html' %}
({% load static %}
{% block title %}Checkout){% endblock %}
{% block content %}

    <h3>ОФОРМЛЕНИЕ ЗАКАЗА</h3>
{%for product in cart_product  %}
    <h5>{{ product.product }}</h5>

    <h3></h3>
    <h3>{{ product.product.quantity }}</h3>
    {% for pr in product.product.productimage_set.all %}
            <img class="product-image" src="{{ pr.image.url }}" alt="{{ product.product.name }}">

        {% endfor %}
    <h3>Сумма:{{ product.product_price }}</h3>


    {% endfor %}
    {%for addon in cart_addon  %}
    <h5>{{ addon.addon }}</h5>


    <h3>{{ addon.addon_price }}</h3>
    <h3>{{ addon.addon.quantity }}</h3>

    {% endfor %}
    {% if total %}
    <h3>К оплате : {{ total }}</h3>
    {% endif %}
    {% csrf_token %}
    <form action="{%  url 'cart:make_order' %}" method="post">
    {% csrf_token %}

    {%  for field in form %}
          <div class="form-row">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{field }}
          {% if errors%}
              {% for error in errors %}
                  <p class="error-message">{{ error }}</p>
              {% endfor %}
          {% endif %}
          </div>
      {% endfor %}

      {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
               <p class="error-message">{{ error }}</p>
          {% endfor %}
      {% endif %}
    <input type="submit" value="Оформить заказ">
    </form>
{% endblock%}