django_diplom/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('addcart/<slug:product_slug>/', views.add_to_cart, name='add_to_cart'),
    path('addcart_addon/<slug:addon_slug>/', views.add_to_cart_addon, name='add_to_cart_addon'),

    path('showcart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
   path('makeorder/', views.MakeOrder, name='make_order'),

    path('addcart/removeproduct/<slug:product_slug>/', views.remove_product, name='remove_product'),
    path('addcart/change_quantity/<slug:product_slug>/', views.change_quantity, name='change_quantity'),
path('addcart_addon/removeproduct/<slug:addon_slug>/', views.remove_addon, name='remove_addon'),
    path('addcart_addon/change_quantity/<slug:addon_slug>/', views.change_quantity_addon, name='change_quantity_addon'),

]

django_diplom/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),
    path('men/', views.MenTemplate.as_view(), name='Men'),
    path('women/', views.women, name='Women'),
    path('kids/', views.kids, name='Kids'),
    path('accessories/', views.accessory, name='Accessory'),

    path('category/<slug:category_slug>/', views.one_cat, name='one_cat'),
    path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),

    # path('ad/', views.addons, name='addons'),
    # path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),
    # path('onec/', views.one_cat, name='one_cat'),
    # path('onec/<slug:product_slug>/', views.product_views, name='product'),

    # path('product/', views.product_views, name='product'),
    # path('category/<slug:category_slug>/', views.category_view, name='category_view'),
    # path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    # path('category/<slug:category_slug>/', views.cat_review, name='cat_review'),
    # path('product/<slug:product_slug>/', views.prod_review, name='prod_review'),
    # path('cat/<slug:category_slug>/', views.table, name='table'),

]

django_diplom/django_diplom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views
from django_diplom import settings




urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('authentication.urls')),
    path('cart/', include('cart.urls')),
    path('news/', include('news.urls')),
    path('contactwithus/', include('contact_form.urls'))

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_diplom/catalog/models.py
from colorfield.fields import ColorField
from django.db import models

gender = (
    ('male', 'male'),
    ('female', 'female'),
    ('kids', 'kids'),
    ('accessory', 'accessory'),
)

COLOR_CHOICES = [
    ("#FFFFFF", "white"),
    ("#000000", "black")

]


class Category(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='описание')
    slug = models.SlugField(max_length=40, unique=True)
    gender = models.CharField(default='', max_length=9, choices=gender, verbose_name="gender")

    def __str__(self):
        return self.name


class Addon(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='описание')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='цена')
    slug = models.SlugField(max_length=40, unique=True)
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name


class AddonImage(models.Model):
    image = models.ImageField(blank=True, null=True, upload_to='images', help_text='150x150px',
                              verbose_name='изображение')
    addon = models.ForeignKey('Addon', on_delete=models.CASCADE)


class Product(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование')
    description = models.TextField(max_length=256, verbose_name='описание')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='цена')
    slug = models.SlugField(max_length=40, unique=True)
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)
    addons = models.ManyToManyField("Addon", blank=True)
    quantity = models.PositiveIntegerField(default=1)




    def __str__(self):
        return self.name


class ProductImage(models.Model):
    image = models.ImageField(blank=True, null=True, upload_to='images', help_text='150x150px',
                              verbose_name='изображение')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)


class ProductSpecification(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование характеристики')

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

    def __str__(self):
        return self.name


class ProductSpecificationValue(models.Model):
    specification = models.ForeignKey('ProductSpecification', on_delete=models.CASCADE)
    value = models.CharField(max_length=128, verbose_name='Значение характеристики')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Значение характеристики'
        verbose_name_plural = 'Значения характеристик'

    def __str__(self):
        return f'{self.specification.name} - {self.value}'


class AddonSpecification(models.Model):
    name = models.CharField(max_length=32, verbose_name='Наименование характеристики')

    class Meta:
        verbose_name = 'Характеристика'
        verbose_name_plural = 'Характеристики'

    def __str__(self):
        return self.name


class AddonSpecificationValue(models.Model):
    specification = models.ForeignKey('AddonSpecification', on_delete=models.CASCADE)
    value = models.CharField(max_length=128, verbose_name='Значение характеристики')
    product = models.ForeignKey('Addon', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Значение характеристики'
        verbose_name_plural = 'Значения характеристик'

    def __str__(self):
        return f'{self.specification.name} - {self.value}'

django_diplom/catalog/forms.py
from django.contrib.auth.models import User
from django.forms import forms

django_diplom/catalog/views.py
from collections import defaultdict
from typing import Any, Dict

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.handlers.wsgi import WSGIRequest
from django.db.models import Count
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect

from django.views.generic import TemplateView

from cart.models import CartProduct, CartAddon
from catalog.models import Category, Product, Addon


class HomeTemplateView(TemplateView):
    template_name = "catalog/home.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.annotate(
            total=Count('product', distinct=True) + Count('addon', distinct=True))

        return context


@login_required
def home(request):
    cat = Category.objects.annotate(Count('product'))
    return render(
        request,
        'catalog/home.html',
        {
            "categories": cat,

        }
    )


class MenTemplate(TemplateView):
    template_name = "catalog/Men.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context: Dict[str, Any] = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.annotate(total=Count('product', distinct=True)).filter(gender='male')

        return context


def men(request):
    cat = Category.objects.annotate(Count('product'))
    return render(
        request,
        'catalog/Men.html',
        {
            "categories": cat,

        }
    )


def kids(request):
    cat = Category.objects.filter(gender='kids')
    return render(
        request,
        'catalog/Kids.html',
        {
            "categories": cat,

        }
    )


def women(request):
    cat = Category.objects.filter(gender='female')
    return render(
        request,
        'catalog/Women.html',
        {
            "categories": cat,
        }
    )


def accessory(request):
    cat = Category.objects.filter(gender='accessory')
    return render(
        request,
        'catalog/Women.html',
        {
            "categories": cat,
        }
    )


def addon(request):
    addon = Category.objects.annotate(Count('addon'))
    return addon


def cat(request: WSGIRequest, category_slug: str) -> HttpResponse:
    try:

        category: Category = (Category.objects.prefetch_related("product_set").get(slug=category_slug))
    except Category.DoesNotExist:
        raise Http404
    return render(request, 'catalog/home.html', {'category': category})


@login_required
def one_cat(request, category_slug):
    cat = Category.objects.prefetch_related("product_set").prefetch_related("addon_set__product_set").filter(
        slug=category_slug).first()

    return render(
        request,
        'catalog/one_categories.html',
        {"categories": cat,
         "addons": addon(request)
         }

    )


def prod_view(request, product_slug):
    product = Product.objects.prefetch_related("addons").prefetch_related("addons__category").filter(
        slug=product_slug).first()

    mapper = defaultdict(list)

    for a in product.addons.all():
        mapper[a.category.name].append(a)

    return render(
        request,
        'catalog/product.html',
        {
            "products": product,
            "addons_mapper": dict(mapper),
            'is_product_in_cart': is_product_in_cart(product, request.user)

        }
    )


def addon_view(request, addon_slug):
    add = Addon.objects.filter(slug=addon_slug).first()

    return render(
        request,
        'catalog/addon.html',
        {
            "addon": add,
            'is_addon_in_cart': is_addon_in_cart(add, request.user)

        }
    )


def is_product_in_cart(product, user):
    is_exists = CartProduct.objects.filter(product=product, cart__user=user,
                                           cart__checked_out=False).exists()
    return is_exists


def is_addon_in_cart(addon, user):
    is_addon_exists = CartAddon.objects.filter(addon=addon, cart__user=user,
                                               cart__checked_out=False).exists()
    return is_addon_exists

django_diplom/catalog/templates/catalog/Accessory.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} Аксессуары {% endblock %}
{% block content %}
    <div>

    {% for c in categories %}

        <ul>
            <li> <a href="{% url 'catalog:one_cat' c.slug %}">{{c.name}} ({{ c.total  }})  </a></li>

        </ul>

        {% endfor %}
    </div>
{% endblock %}

django_diplom/catalog/templates/catalog/Kids.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} Детское {% endblock %}
{% block content %}
    <div>

    {% for c in categories %}

        <ul>
            <li> <a href="{% url 'catalog:one_cat' c.slug %}">{{c.name}} ({{ c.total  }})  </a></li>

        </ul>

        {% endfor %}
    </div>
{% endblock %}

django_diplom/catalog/templates/catalog/Men.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} Мужское {% endblock %}
{% block content %}
    <div>

    {% for c in categories %}

        <ul>
            <li> <a href="{% url 'catalog:one_cat' c.slug %}">{{c.name}} ({{ c.total  }})  </a></li>

        </ul>

        {% endfor %}
    </div>
{% endblock %}

django_diplom/catalog/templates/catalog/Women.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} Женское {% endblock %}
{% block content %}
    <div>

    {% for c in categories %}

        <ul>
            <li> <a href="{% url 'catalog:one_cat' c.slug %}">{{c.name}} ({{ c.total  }})  </a></li>

        </ul>

        {% endfor %}
    </div>
{% endblock %}

django_diplom/catalog/templates/catalog/addon.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} {{ products.name}} {% endblock %}
{% block content %}
<div>


    <div>
          <h3>{{addon.name }}</h3>
    <h5>{{ addon.description }}</h5>
    </div>

     {% if is_addon_in_cart %}
<a class="button" href="{% url 'cart:cart'  %}">перейти в корзину</a>
     {% else %}


<a class="button" href="{% url 'cart:add_to_cart_addon' addon.slug %}">add to cart</a>
{% endif %}
</div>
{% endblock %}

django_diplom/catalog/templates/catalog/catalog_base.html
{% extends 'base.html' %}

    {% block styles  %}
       {% load static %}
       {{ block.super }}
       <link rel="stylesheet" href="{% static 'catalog/styles.css' %}">
    {% endblock %}

django_diplom/catalog/templates/catalog/home.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} домашняя страница {% endblock %}

django_diplom/catalog/templates/catalog/home2.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} домашняя страница {% endblock %}
{% block content %}
    <div>

    {% for c in categories %}
        <ul>
            <li> <a href="{% url 'catalog:one_cat' c.slug %}">{{c.name}} ({{ c.total  }})  </a></li>

        </ul>
        {% endfor %}
    </div>
{% endblock %}

django_diplom/catalog/templates/catalog/one_categories.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} {{ categories.name }} {% endblock %}
{% block content %}
 <div>
 {% if categories %}
  <h3> {{ categories.description }}</h3>
    {% for pr in categories.product_set.all %}
        <ul>
            <li> <a href="{% url 'catalog:prod_view' pr.slug %}">{{pr.name}}</a></li>


        </ul>
        {% endfor %}
     {% for add in categories.addon_set.all %}
         <ul>
                        <li> <a href="{% url 'catalog:addon_view' add.slug %}">{{add.name}}</a></li>
         </ul>
            {% endfor %}
     {% endif %}
{% comment %} {% if addons %}
    {% for add in addons %}
        <ul>
            <li> <a href="{% url 'catalog:addon_view' add.slug %}">{{add.name}}</a></li>

        </ul>
        {% endfor %}

{% endif %}{% endcomment %}

    </div>
{% endblock %}

django_diplom/catalog/templates/catalog/product.html
{% extends 'catalog/catalog_base.html' %}
{% block title %} {{ products.name}} {% endblock %}
{% block content %}
<div>
    <h3>{{ products.name }}</h3>
    <h5>{{ products.description }}</h5>
{% comment %}<form method="get" action="{% url 'cart:add_to_cart' %}">
    <input type="number" name="quantity">
    <button
            type="submit"
            class="button"
            href="{% url 'cart:add_to_cart' product.id %}"
    >Добавить в корзину</button>


</form>{% endcomment %}
 <div>
     {% if is_product_in_cart %}
<a class="button" href="{% url 'cart:cart'  %}">перейти в корзину</a>
     {% else %}

<a class="button" href="{% url 'cart:add_to_cart' products.slug %}">add to cart</a>
     {% endif %}
 </div>

    {% if products.productspecificationvalue_set.all %}
        <h4>Характеристики</h4>
        <table>
        <tr>
            <th>Характеристика</th>
            <th>Значение</th>
        </tr>
        {% for specification_value in products.productspecificationvalue_set.all %}
          <tr>
             <td> {{ specification_value.specification.name }}</td>
           <td>{{ specification_value.value }}  </td>
          </tr>
        {% endfor %}


        </table>
    {% endif %}

</div>

    {% for product_image in products.productimage_set.all %}
<div>
    <img class="product-image" src="{{ product_image.image.url }}" alt="{{ products.name }}">

</div>
    {% endfor %}
{% if addons_mapper %}
<h3>купи дополнительно:</h3>

{% for cat_name ,addons in addons_mapper.items %}
<div>
<h5>{{ cat_name }}</h5>
    {% for addon in addons %}

    <ul>
        <li> <a href="{% url 'catalog:addon_view' addon.slug %}">{{addon.name}}</a></li>


        </ul>
</div>
    {% endfor %}
{% endfor %}
{% endif %}
{% endblock %}

django_diplom/catalog/templates/catalog/table.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Таблица</title>
</head>
<body>


<table>
      <tr>
          <th>id</th>
          <th>Наименование</th>
          <th>описание</th>
      </tr>

{% for pr in products %}
    <tr>
        <td>{{pr.id}}</td>
        <td>{{ pr.name }}</td>
    <td>{{ pr.description }}</td>
    </tr>
{% endfor %}
</table>
</body>
</html>