django_diplom/authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'

urlpatterns = [
    path('reg/', views.reg, name='reg'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('myacc/', views.account, name='account'),


]

django_diplom/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('addcart/<slug:product_slug>/', views.add_to_cart, name='add_to_cart'),
    path('addcart_addon/<slug:addon_slug>/', views.add_to_cart_addon, name='add_to_cart_addon'),

    path('showcart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
   path('makeorder/', views.MakeOrder, name='make_order'),

    path('addcart/removeproduct/<slug:product_slug>/', views.remove_product, name='remove_product'),
    path('addcart/change_quantity/<slug:product_slug>/', views.change_quantity, name='change_quantity'),
path('addcart_addon/removeproduct/<slug:addon_slug>/', views.remove_addon, name='remove_addon'),
    path('addcart_addon/change_quantity/<slug:addon_slug>/', views.change_quantity_addon, name='change_quantity_addon'),

]

django_diplom/catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),
    path('men/', views.MenTemplate.as_view(), name='Men'),
    path('women/', views.women, name='Women'),
    path('kids/', views.kids, name='Kids'),
    path('accessories/', views.accessory, name='Accessory'),

    path('category/<slug:category_slug>/', views.one_cat, name='one_cat'),
    path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),

    # path('ad/', views.addons, name='addons'),
    # path('addon/<slug:addon_slug>/', views.addon_view, name='addon_view'),
    # path('onec/', views.one_cat, name='one_cat'),
    # path('onec/<slug:product_slug>/', views.product_views, name='product'),

    # path('product/', views.product_views, name='product'),
    # path('category/<slug:category_slug>/', views.category_view, name='category_view'),
    # path('product/<slug:product_slug>/', views.prod_view, name='prod_view'),
    # path('category/<slug:category_slug>/', views.cat_review, name='cat_review'),
    # path('product/<slug:product_slug>/', views.prod_review, name='prod_review'),
    # path('cat/<slug:category_slug>/', views.table, name='table'),

]

django_diplom/django_diplom/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from catalog import views
from django_diplom import settings




urlpatterns = [

    path('', views.HomeTemplateView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('auth/', include('authentication.urls')),
    path('cart/', include('cart.urls')),
    path('news/', include('news.urls')),
    path('contactwithus/', include('contact_form.urls'))

]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_diplom/authentication/models.py
import os
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser


def get_file_path(instance, image_name):
    ext = image_name.split('.')[-1]
    new_name = f'{uuid.uuid4()}.{ext}'
    return os.path.join('uploads', 'avatars', new_name)


class User(AbstractUser):
    avatar = models.ImageField(verbose_name='аватарка', upload_to=get_file_path, blank=True, null=True)
    email = models.EmailField(verbose_name='email', unique=True)
# Create your models here.

django_diplom/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.core.exceptions import ValidationError
from django.db.models import Q

from django_diplom import settings

User = get_user_model()


class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput, label='пароль')
    password2 = forms.CharField(widget=forms.PasswordInput, label='пароль')

    class Meta:
        model = User
        fields = ['email', 'avatar']
        labels = {

            'email': 'email'

        }


def clean_password2(self):
    if self.cleaned_data['password1'] != self.cleaned_data['password2']:
        raise ValidationError(
            'пароли должны совпадать'
        )
    return self.cleaned_data['password2']


def clean(self):
    user = User.objects.filter(
        email=self.cleaned_data['email']).first()
    if user:
        raise ValidationError('пользователь с такими учетными данными уже существует ')
    return super().clean()


class LoginForm(forms.Form):
    email_or_username = forms.CharField(label='email или имя пользователя')
    password = forms.CharField(label='пароль', widget=forms.PasswordInput)

    def clean(self):
        user = authenticate(
            email=self.cleaned_data['email_or_username'],
            username=self.cleaned_data['email_or_username'],
            password=self.cleaned_data['password']
        )
        if not user:
            raise ValidationError('Введенные данные не верны ')
        return self.cleaned_data

django_diplom/authentication/views.py
from django.contrib.auth import get_user_model, authenticate, login as login_user, logout as logout_user
from django.shortcuts import render, redirect
from django.urls import reverse

from authentication.forms import RegistrationForm, LoginForm

User = get_user_model()


def reg(request):
    if request.user.is_authenticated:
        return redirect(reverse('catalog:home'))

    if request.method == 'POST':
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password2'])
            user.save()
            return redirect(reverse('catalog:home'))
    else:
        form = RegistrationForm()

    return render(request,
                  'authentication/reg.html',
                  {'form': form}

                  )


def login(request):
    if request.user.is_authenticated:
        return redirect(reverse('catalog:home'))

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request,
                                email=form.cleaned_data['email_or_username'],
                                username=form.cleaned_data['email_or_username'],
                                password=form.cleaned_data['password']
                                )
            if user:
                redirect_url = request.GET.get('next') or reverse('catalog:home')
                login_user(request, user)
                return redirect(redirect_url)
    else:
        form = LoginForm()
    next_url = request.GET.get('next', '')
    return render(
        request,
        'authentication/login.html',
        {'form': form, 'next': next_url}
    )


def logout(request):
    logout_user(request)
    return redirect(reverse('catalog:home'))

def account(request):
    user = request.user
    return render(
        request,
        'authentication/account.html',
        {'user': user}
    )

django_diplom/authentication/templates/authentication/account.html
{% extends 'authentication/auth_base.html' %}

{% load widget_tweaks %}
{% block title %} Регистрация {% endblock %}
{% block content %}
    <div>
        {% if user.is_authenticated %}
            {% if user.is_authenticated %}
                {% if user.username %}

                    <h3>username:{{ user.username }}</h3>
                {% endif %}
                <h3> email: {{ user.email }}</h3>

                {% if user.avatar %}
                    {{ user.username }}

                    <img src="{{ user.avatar.url }}" height="25" width="25">
                {% endif %}
                <a href="{% url 'authentication:logout' %}">Выйти</a>

            {% else %}

                <a href="{% url 'authentication:login' %}">Войти</a>

                </div>
            {% endif %}
            {% else %}
            <div>
            Вы еще не вошли в аккаунт,хотите войти?
            <a href="{% url 'authentication:login' %}">Войти</a>
            </div>
            <a href="{% url 'catalog:home' %}">Вернуться на домашнюю страницу</a>



        {% endif %}
{% endblock %}

django_diplom/authentication/templates/authentication/auth_base.html
{% extends 'base.html' %}

    {% block styles  %}
       {% load static %}
       {{ block.super }}
       <link rel="stylesheet" href="{% static 'authentication/styles.css' %}">
    {% endblock %}

django_diplom/authentication/templates/authentication/login.html
{% extends 'authentication/auth_base.html' %}

{%  load widget_tweaks %}
{% block title %} Login {% endblock %}
{% block content %}
      <form
              method="post"
              action="{% url 'authentication:login' %}{% if next %}?next={{ next }}{% endif %}"

      >
          {% csrf_token %}

      {%  for field in form %}
          <div class="form-row">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{field }}
          {% if errors%}
              {% for error in errors %}
                  <p class="error-message">{{ error }}</p>
              {% endfor %}
          {% endif %}
          </div>
      {% endfor %}

      {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
               <p class="error-message">{{ error }}</p>
          {% endfor %}
      {% endif %}
{% comment %}
       {{ form.as_p }}
{% endcomment %}
          <button type="submit">Войти</button>

      <p>Если у вас еще нет аккаунта,зарегистрируйтесь</p>
      <a href="{% url 'authentication:reg' %}">Зарегистрироваться</a>
      </form>

{% endblock %}

django_diplom/authentication/templates/authentication/password_change_done.html
{% extends 'authentication/auth_base.html'%}

{% block title %}Password changed{% endblock %}

{% block content %}
    <h1>Password changed</h1>
    <p>Your password has been successfully changed.</p>
{% endblock %}

django_diplom/authentication/templates/authentication/password_change_form.html
{% extends 'authentication/auth_base.html' %}

{% block title %}Change you password{% endblock %}

{% block content %}
    <h1>Change you password</h1>
    <p>Use the form below to change your password.</p>
    <form action="." method="post">
        {{ form.as_p }}
        <p><input type="submit" value="Change"></p>
        {% csrf_token %}
    </form>
{% endblock %}

django_diplom/authentication/templates/authentication/reg.html
{% extends 'authentication/auth_base.html' %}

{%  load widget_tweaks %}
{% block title %} Регистрация {% endblock %}
{% block content %}
      <form
              method="post"
              action="{% url 'authentication:reg' %}"
              enctype="multipart/form-data"

      >
          {% csrf_token %}

      {%  for field in form %}
          <div class="form-row">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {{field }}
          {% if errors%}
              {% for error in errors %}
                  <p class="error-message">{{ error }}</p>
              {% endfor %}
          {% endif %}
          </div>
      {% endfor %}

      {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
               <p class="error-message">{{ error }}</p>
          {% endfor %}
      {% endif %}
{% comment %}
       {{ form.as_p }}
{% endcomment %}
       <button type="submit">Зарегистрироваться</button>


      <p>Есть аккаунт?</p>
      <a href="{% url 'authentication:login' %}">Войти</a>

      </form>

{% endblock %}